serviceName: da-otel-agent-service
sampler: "parentbased_traceidratio"
sampleRatio: 0.01
readOnly: false
rules:
  - exclude:
    - http.target: "/metrics"
      http.method: "GET"
  - exclude:
    - http.target: "/metrics/.+"
      http.method: "POST"
