# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle
name: Build and publish release

on:
  release:
    types: [created]
  workflow_dispatch:
      release_version:
        type: string
        description: Release version.
        required: false
        default: "1.0.0"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle validate wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Gradle build
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        arguments: build --no-daemon -PGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -PGITHUB_ACTOR=${{ github.actor }}

    - name: Gradle publish
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        arguments: publish --no-daemon -Pversion=${{needs.package-version.outputs.version}} -PGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -PGITHUB_ACTOR=${{ github.actor }}