name: Vulnerability Scan

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle validate wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Gradle build agent and service
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        arguments: build --no-daemon
  
    - name: Build an image from Dockerfile
      run: |
        cp service/build/libs/service.jar .
        docker build -t da-otel-agent-configuration-service:${{ github.sha }} .
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: da-otel-agent-configuration-service:${{ github.sha }}
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
